### PR TITLE
Correct a few more typos and update some sections of text

### PR DESCRIPTION
**Pull request by LaurentAjdnik**
Corrects a few more typos (not addressed in #72).

Updates a few sections of text.

Aligns spelling of packages names.

Updates mentions about the CLA bot.

### CODE REVIEW

**Comment by LaurentAjdnik** [comment]
Might close #70.

**Comment by idavis** [comment]
Hi @LaurentAjdnik - thanks for these updates. Could you please update your branch? We've had to rename one of the projects and the package names are in line with the changes you have made here. Any links or references to `jit` are now the `pyqir-evaluator`.

**Comment by LaurentAjdnik** [comment]
Can be cancelled (replaced by #86).

**Comment by idavis** [comment]
Closing as superseded.

**Pull request closed without merging**
