### PR TITLE
Correct instructions docstrings in parser.py

### PR DESCRIPTION
**Pull request by LaurentAjdnik**
Replace occurrences of `Instr` mistyped `Intr` in doctrings.

Replace `QirLShrIntr` by `QirAShrInstr` in the docstring for the `QirAShrInstr` class.

### CODE REVIEW

**Comment by idavis** [comment]
Hi @LaurentAjdnik - thanks for the PR. As soon as the CLA infrastructure is set up we'll process this PR. Sorry for the delay.

**Comment by idavis** [comment]
Hi @LaurentAjdnik - the CLA is now setup and can be seen in the list of checks. Sorry about the delay.

**Comment by LaurentAjdnik** [comment]
> Hi @LaurentAjdnik - the CLA is now setup and can be seen in the list of checks. Sorry about the delay.

Thanks @idavis! CLA signed. It seems that, in between, files have changed drastically. Should we cancel this PR and do it again on `pyqir-parser/pyqir/parser/_parser.py`?

**Comment by idavis** [comment]
@LaurentAjdnik - I think you have the best idea right now. I'm very sorry it took so long to get the infrastructure in place. I'll close this PR and keep an eye out for a new one. Thank you for your patience and help.

**Pull request closed without merging**
